# Generated by Django 5.2 on 2025-04-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.URLField(blank=True)),
                ('power', models.IntegerField(help_text='Potencia en Watts')),
                ('efficiency', models.DecimalField(decimal_places=2, help_text='Porcentaje de eficiencia', max_digits=4)),
                ('panel_type', models.CharField(choices=[('Monocristalino', 'Monocristalino'), ('Policristalino', 'Policristalino'), ('Amorfo', 'Amorfo')], max_length=50)),
            ],
        ),
    ]
